# https://gleam.run/writing-gleam/gleam-toml/.

name = "chess_engine_rose_colored_glasses"
version = "1.0.0"
target = "erlang"
licences = ["MIT"]
description = "My submission to isaacharrisholt/gleam-chess-tournament"
repository = { type = "github", user = "lue_bird", repo = "https://github.com/lue-bird/gleam-chess-bot-rose-colored-glasses" }
links = [{ title = "isaacharrisholt/gleam-chess-tournament", href = "https://github.com/isaacharrisholt/gleam-chess-tournament" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
wisp = ">= 1.5.3 and < 2.0.0"
mist = ">= 4.0.7 and < 5.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
